Repository Cap-go/capgo, pull requests merged in 2023-09, with the labels that each got.

#329 Fix base.sql
  supabase/migrations/20230815171919_base.sql
Labels: 💰 Rewarded

#338 add billing cycle
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/fr.yml
  locales/id.yml
  locales/it.yml
  locales/ja.yml
  locales/ko.yml
  locales/pl.yml
  locales/pt-BR.yml
  locales/ru.yml
  locales/tr.yml
  locales/vi.yml
  locales/zh-CN.yml
  src/pages/dashboard/settings/Plans.vue
Labels: 💰 Rewarded, 🙋 Bounty claim

#345 Add E2E tests and precommit hooks
  .env.exemple
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  src/pages/login.vue
  tests/login.spec.ts
Labels: 🙋 Bounty claim

#347 feat: Add GitHub action gpt
  .github/workflows/chatgpt-review.yml
Labels: 🙋 Bounty claim

#362 fix: Fix devices tab name in channel
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/fr.yml
  locales/id.yml
  locales/it.yml
  locales/ja.yml
  locales/ko.yml
  locales/pl.yml
  locales/pt-BR.yml
  locales/ru.yml
  locales/tr.yml
  locales/vi.yml
  locales/zh-CN.yml
  src/pages/app/p/[p]/channel/[channel].vue
Labels: 🙋 Bounty claim

#364 Test updates endpoint
  .github/workflows/test_backend.yml
  .vscode/settings.json
  package.json
  supabase/.env.exemple
  supabase/.env.exemple.redis
  supabase/functions/_utils/plunk.ts
  supabase/functions/updates/index.ts
  supabase/seed.sql
  tests_backend/gh_actions/docker.sh
  tests_backend/gh_actions/minio.sh
  tests_backend/run_backend_tests.ts
  tests_backend/tests/updates_test.ts
  tests_backend/utils.ts
Labels: 🙋 Bounty claim

#383 fix: Unable to delete apps from dashboard
  src/components/dashboard/AppCard.vue
Labels: 🙋 Bounty claim

#392 Add Billing Stats
  src/layouts/settings.vue
  src/pages/dashboard/settings/Plans.vue
  src/pages/dashboard/settings/Usage.vue
Labels: 🙋 Bounty claim
