Repository Cap-go/capgo, pull requests merged in 2023-10, with the labels that each got.

#397 CLI tests
  .github/workflows/test.yml
  .github/workflows/test_backend.yml
  CONTRIBUTING.md
  package.json
  playwright.config.ts
  scripts/utils.mjs
  supabase/.env.example
  supabase/.env.example.redis
  tests/bundle.spec.ts
  tests/login.spec.ts
  tests_backend/gh_actions/minio.sh
  tests_backend/run_backend_tests.ts
  tests_backend/tests/backend/updates_test.ts
  tests_backend/tests/cli/test_cli.ts
  tests_backend/tests/updates_test.ts
  tests_backend/utils.ts
Labels: 💰 Rewarded, 🙋 Bounty claim

#404 Remove foreign key
  src/components/tables/DeviceTable.vue
  src/pages/app/p/[p]/d/[device].vue
  supabase/migrations/20230930062908_drop_constraint.sql
Labels: 🙋 Bounty claim

#399 Fix: use Zod validation for JSON requests (supersedes #385)
  package.json
  supabase/functions/_utils/utils.ts
  supabase/functions/stats/index.ts
  supabase/functions/updates/index.ts
  tests_backend/zod.test.ts
Labels: 🙋 Bounty claim

#425 add resend email + auto translate
  locales/README.md
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/fr.yml
  locales/id.yml
  locales/it.yml
  locales/ja.yml
  locales/ko.yml
  locales/package.json
  locales/pl.yml
  locales/pnpm-lock.yaml
  locales/pt-BR.yml
  locales/ru.yml
  locales/tr.yml
  locales/translate-data.json
  locales/translate.ts
  locales/vi.yml
  locales/zh-CN.yml
  src/pages/login.vue
  src/pages/onboarding/confirm_email.vue
  src/pages/register.vue
  src/pages/resend_email.vue
  vite.config.ts
Labels: 💰 Rewarded
